name: Build on push to pr

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'examples/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: marlin-build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
